# aws cloudformation delete-stack --stack-name iris-model-dev
# aws cloudformation create-stack --stack-name iris-model-dev --template-body file://deploy-model-dev.yml --parameters file://deploy-model-dev.json

Description: Deploy a model at Sagemaker
Parameters:
  ImageRepoUri:
    Type: String
    Description: Uri of the docker (ECR) model image
  ModelName:
    Type: String
    Description: Name of the model
  TrainJobId:
    Type: String
    Description: Id of the Codepipeline + SagemakerJobs
  MLOpsRoleArn:
    Type: String
    Description: The role for executing the deployment
  VariantName:
    Type: String
    Description: Name of the endpoint variant

Resources:
  Model:
    Type: "AWS::SageMaker::Model"
    Properties:
      ModelName: !Sub mlops-${ModelName}-dev-${TrainJobId}
      PrimaryContainer:
        Image: !Ref ImageRepoUri
        ModelDataUrl: !Sub s3://sagemaker-${AWS::Region}-${AWS::AccountId}/${ModelName}/mlops-${ModelName}-${TrainJobId}/output/model.tar.gz
        Env:
            SAGEMAKER_PROGRAM: "inference.py"
      ExecutionRoleArn: !Ref MLOpsRoleArn

  EndpointConfig:
    Type: "AWS::SageMaker::EndpointConfig"
    Properties:
      ProductionVariants:
        - InitialInstanceCount: 1
          InitialVariantWeight: 1.0
          InstanceType: ml.t2.medium
          ModelName: !GetAtt Model.ModelName
          VariantName: !Ref VariantName
      EndpointConfigName: !Sub mlops-${ModelName}-dec-${TrainJobId}
      Tags:
        - Key: Name
          Value: !Sub mlops-${ModelName}-dec-${TrainJobId}
    DependsOn: Model

  Endpoint:
    Type: "AWS::SageMaker::Endpoint"
    Properties:
      EndpointName: !Sub mlops-${ModelName}-dev-${TrainJobId}
      EndpointConfigName: !GetAtt EndpointConfig.EndpointConfigName
      Tags:
        - Key: Name
          Value: !Sub mlops-${ModelName}-dev-${TrainJobId}
    DependsOn: EndpointConfig
